== Computing Basics

This is a compilation of _basic_ things everyone should know about
computing, on various related topics.

We are compiling a list of basic "things people should know" about
computing and information technology, generally for professional and
academic careers. The target audience is "non-technical", smart people
who know little or nothing about the technical details of computing, the
Internet, security, etc. or how any of it actually "works".

These "must know" basics are in
https://github.com/brianhigh/computing-basics/wiki[the wiki].

=== The Computing Basics Team

Thanks to the following people who have contributed to this resource (in
no particular order):

_Brian High, Wilson Waldrop, Doug Hayman, Eric Kool-Brown, Thayer York,
Richard Letts, Travis Mitchell, Chance Reschke, Bryce Livingston, David
Brodbeck, Carl Riches, John Yocum, Martin Criminale, Nathan Dors,
Michael Burdett, Ken Lowe_

=== Copyright, License and Disclaimer

Copyright © The https://github.com/brianhigh/computing-basics[Computing
Basics Team]. This information is provided for educational purposes
only. See
https://github.com/brianhigh/computing-basics/blob/master/LICENSE[LICENSE]
for more information.
https://creativecommons.org/licenses/by/4.0/[Creative Commons
Attribution 4.0 International Public License].
